name: Expunge
version: '${version}'
main: me.chimkenu.expunge.Expunge
api-version: 1.20
authors: [ Chimkenu ]
description: A Left4Dead inspired Minecraft mini-game
commands:
  expunge:
    description: Expunge command
    usage: /<command> [tutorial|stats|start|stop|get|spawn|reload]
permissions:
  expunge:
    default: true
  expunge.tutorial:
    default: true
  expunge.stats.player:
    default: true
  expunge.stats.game:
    default: op
  expunge.start:
    default: op
  expunge.stop:
    default: op
  expunge.get:
    default: op
  expunge.spawn:
    default: op
  expunge.reload:
    default: op
  expunge.*:
    default: op
    children:
      expunge: true
      expunge.tutorial: true
      expunge.stats.player: true
      expunge.stats.game: true
      expunge.start: true
      expunge.stop: true
      expunge.get: true
      expunge.spawn: true
      expunge.reload: true